### ISSUE TITLE
ReadlInt function incorrectly reads positive values

### ISSUE THREAD

**Issue by pyxiscloud** [dyrkin/composer#1]
Hi
Found a bug in a code, that cause wrong value Reading

Change ReadInt function to this:

```go
func (f *Composer) ReadInt(endianness binary.ByteOrder, size int) int64 {

	var v int64
	buf := make([]uint8, size)
	f.r.Read(buf)
	if endianness == binary.BigEndian {
		for i := 0; i < size; i++ {
			t := buf[i]
			v = v | int64((t))<<byte((size-i-1)*8)
		}
	} else {
		for i := 0; i < size; i++ {
			t := buf[i]
			v = v | int64((t))<<byte(i*8)
		}
	}
	return v
}
```

**Comment by dyrkin** [comment]
Hi,
Then I'll not be able to read negative values.

Could you share your values and what you expect?

**Comment by dyrkin** [comment]
If you want to read unsigned int use `ReadUint` function

**Comment by pyxiscloud** [comment]
please try Xiaomi Temperature Sensor - it shows negative value at 28 degrees and lower )
maybe bug in the zcl-go? (need to use ReadUint there)

example []byte{0xf9, 0x0a} should give 2809, but we got -7

**Comment by dyrkin** [comment]
That's strange.
Could you post here dump of `model.DeviceIncomingMessage` with this value if you use zigbee-steward?

**Comment by dyrkin** [comment]
Please ignore my previous message.
It seems you are right. The bug exists precisely in the place where you say. I'll try to fix it.

**Comment by dyrkin** [comment]
Please verify the latest version
